# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 496f27df7b4a3161f8fa0b032a2251893ad24ac1810a2da99703aac9dd17d47c84d4237146ba6aeefa576d53de0ef4cec11aa5f2057d6ed8f8db0bd854ef71b9
test:
  secret_key_base: 83e2b631cbfc8c559d0ed831ebdd7e33dcde9186cb842def3ef42ed425e34124f27da07f88376ec42d5d6ab6d494db28048a36310033017cac06d46cde9c4c24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
